/**
 * French capital names per country (ISO-3166-1 alpha-2) for the "Capitales"
 * game mode. A value is either the display name, or [displayName, ...aliases]
 * where aliases are alternate/accepted answers (former names, de-facto seats,
 * English forms, common spellings). The English capital from countries.ts is
 * always accepted too, so gaps here still match.
 */
import { BY_ISO } from "./countries";
import { normalize, levenshtein } from "./normalize";
import type { Difficulty } from "@/types/shared";

type Cap = string | [string, ...string[]];

export const CAPITAL_FR: Record<string, Cap> = {
  AF: "Kaboul",
  AL: "Tirana",
  DZ: "Alger",
  AD: ["Andorre-la-Vieille", "Andorre la Vieille"],
  AO: "Luanda",
  AG: ["Saint John's", "Saint John"],
  AR: "Buenos Aires",
  AM: "Erevan",
  AU: "Canberra",
  AT: "Vienne",
  AZ: "Bakou",
  BS: "Nassau",
  BH: "Manama",
  BD: "Dacca",
  BB: "Bridgetown",
  BY: "Minsk",
  BE: "Bruxelles",
  BZ: "Belmopan",
  BJ: "Porto-Novo",
  BT: "Thimphou",
  BO: ["Sucre", "La Paz"],
  BA: "Sarajevo",
  BW: "Gaborone",
  BR: "Brasília",
  BN: "Bandar Seri Begawan",
  BG: "Sofia",
  BF: "Ouagadougou",
  BI: ["Gitega", "Bujumbura"],
  CV: "Praia",
  KH: "Phnom Penh",
  CM: "Yaoundé",
  CA: "Ottawa",
  CF: "Bangui",
  TD: ["N'Djamena", "Ndjamena"],
  CL: "Santiago",
  CN: ["Pékin", "Beijing"],
  CO: "Bogota",
  KM: "Moroni",
  CG: "Brazzaville",
  CD: "Kinshasa",
  CR: "San José",
  CI: ["Yamoussoukro", "Abidjan"],
  HR: "Zagreb",
  CU: "La Havane",
  CY: "Nicosie",
  CZ: "Prague",
  DK: "Copenhague",
  DJ: "Djibouti",
  DM: "Roseau",
  DO: ["Saint-Domingue", "Santo Domingo"],
  EC: "Quito",
  EG: ["Le Caire", "Caire"],
  SV: "San Salvador",
  GQ: "Malabo",
  ER: "Asmara",
  EE: "Tallinn",
  SZ: ["Mbabane", "Lobamba"],
  ET: "Addis-Abeba",
  FJ: "Suva",
  FI: "Helsinki",
  FR: "Paris",
  GA: "Libreville",
  GM: "Banjul",
  GE: "Tbilissi",
  DE: "Berlin",
  GH: "Accra",
  GR: "Athènes",
  GD: ["Saint-Georges", "Saint Georges"],
  GT: ["Guatemala", "Guatemala City"],
  GN: "Conakry",
  GW: "Bissau",
  GY: "Georgetown",
  HT: "Port-au-Prince",
  HN: "Tegucigalpa",
  HU: "Budapest",
  IS: "Reykjavik",
  IN: ["New Delhi", "Delhi", "Nouvelle Delhi"],
  ID: ["Jakarta", "Djakarta"],
  IR: "Téhéran",
  IQ: "Bagdad",
  IE: "Dublin",
  IL: ["Jérusalem", "Tel Aviv"],
  IT: "Rome",
  JM: "Kingston",
  JP: "Tokyo",
  JO: "Amman",
  KZ: ["Astana", "Noursoultan", "Nur-Sultan"],
  KE: "Nairobi",
  KI: ["Tarawa", "Tarawa-Sud", "South Tarawa"],
  KP: "Pyongyang",
  KR: "Séoul",
  KW: ["Koweït", "Koweït City", "Kuwait City"],
  KG: "Bichkek",
  LA: "Vientiane",
  LV: "Riga",
  LB: "Beyrouth",
  LS: "Maseru",
  LR: "Monrovia",
  LY: "Tripoli",
  LI: "Vaduz",
  LT: "Vilnius",
  LU: "Luxembourg",
  MG: "Antananarivo",
  MW: "Lilongwe",
  MY: "Kuala Lumpur",
  MV: "Malé",
  ML: "Bamako",
  MT: ["La Valette", "Valette", "Valletta"],
  MH: "Majuro",
  MR: "Nouakchott",
  MU: "Port-Louis",
  MX: ["Mexico", "Mexico City"],
  FM: "Palikir",
  MD: ["Chisinau", "Kichinev"],
  MC: "Monaco",
  MN: ["Oulan-Bator", "Oulan Bator", "Ulaanbaatar"],
  ME: "Podgorica",
  MA: "Rabat",
  MZ: "Maputo",
  MM: ["Naypyidaw", "Rangoun", "Yangon"],
  NA: "Windhoek",
  NR: "Yaren",
  NP: "Katmandou",
  NL: "Amsterdam",
  NZ: "Wellington",
  NI: "Managua",
  NE: "Niamey",
  NG: "Abuja",
  MK: "Skopje",
  NO: "Oslo",
  OM: "Mascate",
  PK: "Islamabad",
  PW: "Ngerulmud",
  PA: ["Panama", "Panama City"],
  PG: "Port Moresby",
  PY: "Asuncion",
  PE: "Lima",
  PH: "Manille",
  PL: "Varsovie",
  PT: "Lisbonne",
  QA: "Doha",
  RO: "Bucarest",
  RU: "Moscou",
  RW: "Kigali",
  KN: "Basseterre",
  LC: "Castries",
  VC: "Kingstown",
  WS: "Apia",
  SM: "Saint-Marin",
  ST: ["São Tomé", "Sao Tome"],
  SA: "Riyad",
  SN: "Dakar",
  RS: "Belgrade",
  SC: "Victoria",
  SL: "Freetown",
  SG: "Singapour",
  SK: "Bratislava",
  SI: "Ljubljana",
  SB: "Honiara",
  SO: "Mogadiscio",
  ZA: ["Pretoria", "Le Cap", "Bloemfontein"],
  SS: ["Djouba", "Juba"],
  ES: "Madrid",
  LK: ["Colombo", "Sri Jayawardenepura Kotte"],
  SD: "Khartoum",
  SR: "Paramaribo",
  SE: "Stockholm",
  CH: "Berne",
  SY: "Damas",
  TW: ["Taipei", "Taïpei"],
  TJ: "Douchanbé",
  TZ: ["Dodoma", "Dar es Salaam"],
  TH: "Bangkok",
  TL: "Dili",
  TG: "Lomé",
  TO: ["Nuku'alofa", "Nukualofa"],
  TT: ["Port-d'Espagne", "Port of Spain"],
  TN: "Tunis",
  TR: "Ankara",
  TM: "Achgabat",
  TV: "Funafuti",
  UG: "Kampala",
  UA: ["Kiev", "Kyiv"],
  AE: ["Abou Dabi", "Abu Dhabi"],
  GB: "Londres",
  US: ["Washington", "Washington DC"],
  UY: "Montevideo",
  UZ: "Tachkent",
  VU: "Port-Vila",
  VA: ["Cité du Vatican", "Vatican"],
  VE: "Caracas",
  VN: "Hanoï",
  YE: "Sanaa",
  ZM: "Lusaka",
  ZW: "Harare",
};

const nameOf = (c: Cap): string => (Array.isArray(c) ? c[0] : c);
const variantsOf = (c: Cap): string[] => (Array.isArray(c) ? c : [c]);

/** French capital to display for a country (falls back to the English capital). */
export function capitalFr(isoCode: string): string {
  const c = CAPITAL_FR[isoCode];
  return c ? nameOf(c) : BY_ISO[isoCode]?.capital ?? "";
}

/**
 * Does `guess` name the capital of `isoCode`?
 *  - "normal" : exact (normalized) match against any accepted form
 *  - "easy"   : also Levenshtein ≤ 2 (≤1 for short names)
 * Accepted forms = the French name + its aliases + the English capital.
 */
export function matchCapital(guess: string, isoCode: string, difficulty: Difficulty): boolean {
  const q = normalize(guess);
  if (!q) return false;
  const c = CAPITAL_FR[isoCode];
  const forms = c ? [...variantsOf(c)] : [];
  const en = BY_ISO[isoCode]?.capital;
  if (en) forms.push(en);
  const targets = forms.map(normalize).filter(Boolean);
  if (targets.includes(q)) return true;
  if (difficulty === "normal") return false;
  for (const t of targets) {
    const maxAllowed = t.length <= 5 ? 1 : 2;
    if (levenshtein(q, t) <= maxAllowed) return true;
  }
  return false;
}
