/**
 * 196 UN-recognized sovereign states.
 *   - isoCode:  ISO-3166-1 alpha-2 (used internally + matched against SVG/topojson ids)
 *   - numericId: ISO-3166-1 numeric (the `world-atlas` topojson uses these as `id`)
 *   - aliases:  alternate names / translations / common misspellings (used for matching)
 *
 * Areas are in km² (official + claimed where applicable).
 */
export interface Country {
  isoCode: string;
  numericId: string;
  name: string;
  officialName: string;
  capital: string;
  continent: "Africa" | "Americas" | "Asia" | "Europe" | "Oceania";
  areaKm2: number;
  aliases: string[];
}

export const COUNTRIES: Country[] = [
  { isoCode: "AF", numericId: "004", name: "Afghanistan", officialName: "Islamic Republic of Afghanistan", capital: "Kabul", continent: "Asia", areaKm2: 652230, aliases: ["afghanistan"] },
  { isoCode: "AL", numericId: "008", name: "Albania", officialName: "Republic of Albania", capital: "Tirana", continent: "Europe", areaKm2: 28748, aliases: ["albania", "albanie", "shqiperia"] },
  { isoCode: "DZ", numericId: "012", name: "Algeria", officialName: "People's Democratic Republic of Algeria", capital: "Algiers", continent: "Africa", areaKm2: 2381741, aliases: ["algeria", "algerie", "al-jaza'ir"] },
  { isoCode: "AD", numericId: "020", name: "Andorra", officialName: "Principality of Andorra", capital: "Andorra la Vella", continent: "Europe", areaKm2: 468, aliases: ["andorra", "andorre"] },
  { isoCode: "AO", numericId: "024", name: "Angola", officialName: "Republic of Angola", capital: "Luanda", continent: "Africa", areaKm2: 1246700, aliases: ["angola"] },
  { isoCode: "AG", numericId: "028", name: "Antigua and Barbuda", officialName: "Antigua and Barbuda", capital: "Saint John's", continent: "Americas", areaKm2: 442, aliases: ["antigua and barbuda", "antigua", "antigua et barbuda"] },
  { isoCode: "AR", numericId: "032", name: "Argentina", officialName: "Argentine Republic", capital: "Buenos Aires", continent: "Americas", areaKm2: 2780400, aliases: ["argentina", "argentine"] },
  { isoCode: "AM", numericId: "051", name: "Armenia", officialName: "Republic of Armenia", capital: "Yerevan", continent: "Asia", areaKm2: 29743, aliases: ["armenia", "armenie", "hayastan"] },
  { isoCode: "AU", numericId: "036", name: "Australia", officialName: "Commonwealth of Australia", capital: "Canberra", continent: "Oceania", areaKm2: 7692024, aliases: ["australia", "australie"] },
  { isoCode: "AT", numericId: "040", name: "Austria", officialName: "Republic of Austria", capital: "Vienna", continent: "Europe", areaKm2: 83879, aliases: ["austria", "autriche", "osterreich", "österreich"] },
  { isoCode: "AZ", numericId: "031", name: "Azerbaijan", officialName: "Republic of Azerbaijan", capital: "Baku", continent: "Asia", areaKm2: 86600, aliases: ["azerbaijan", "azerbaidjan", "azerbaïdjan"] },
  { isoCode: "BS", numericId: "044", name: "Bahamas", officialName: "Commonwealth of The Bahamas", capital: "Nassau", continent: "Americas", areaKm2: 13943, aliases: ["bahamas", "the bahamas"] },
  { isoCode: "BH", numericId: "048", name: "Bahrain", officialName: "Kingdom of Bahrain", capital: "Manama", continent: "Asia", areaKm2: 765, aliases: ["bahrain", "bahrein", "bahreïn"] },
  { isoCode: "BD", numericId: "050", name: "Bangladesh", officialName: "People's Republic of Bangladesh", capital: "Dhaka", continent: "Asia", areaKm2: 147570, aliases: ["bangladesh"] },
  { isoCode: "BB", numericId: "052", name: "Barbados", officialName: "Barbados", capital: "Bridgetown", continent: "Americas", areaKm2: 430, aliases: ["barbados", "barbade"] },
  { isoCode: "BY", numericId: "112", name: "Belarus", officialName: "Republic of Belarus", capital: "Minsk", continent: "Europe", areaKm2: 207600, aliases: ["belarus", "bielorussie", "biélorussie", "byelorussia"] },
  { isoCode: "BE", numericId: "056", name: "Belgium", officialName: "Kingdom of Belgium", capital: "Brussels", continent: "Europe", areaKm2: 30528, aliases: ["belgium", "belgique", "belgie", "belgië"] },
  { isoCode: "BZ", numericId: "084", name: "Belize", officialName: "Belize", capital: "Belmopan", continent: "Americas", areaKm2: 22966, aliases: ["belize"] },
  { isoCode: "BJ", numericId: "204", name: "Benin", officialName: "Republic of Benin", capital: "Porto-Novo", continent: "Africa", areaKm2: 114763, aliases: ["benin", "bénin"] },
  { isoCode: "BT", numericId: "064", name: "Bhutan", officialName: "Kingdom of Bhutan", capital: "Thimphu", continent: "Asia", areaKm2: 38394, aliases: ["bhutan", "bhoutan"] },
  { isoCode: "BO", numericId: "068", name: "Bolivia", officialName: "Plurinational State of Bolivia", capital: "Sucre", continent: "Americas", areaKm2: 1098581, aliases: ["bolivia", "bolivie"] },
  { isoCode: "BA", numericId: "070", name: "Bosnia and Herzegovina", officialName: "Bosnia and Herzegovina", capital: "Sarajevo", continent: "Europe", areaKm2: 51197, aliases: ["bosnia and herzegovina", "bosnia", "bosnie", "bosnie-herzegovine", "bosnie-herzégovine"] },
  { isoCode: "BW", numericId: "072", name: "Botswana", officialName: "Republic of Botswana", capital: "Gaborone", continent: "Africa", areaKm2: 581730, aliases: ["botswana"] },
  { isoCode: "BR", numericId: "076", name: "Brazil", officialName: "Federative Republic of Brazil", capital: "Brasília", continent: "Americas", areaKm2: 8515767, aliases: ["brazil", "bresil", "brésil", "brasil"] },
  { isoCode: "BN", numericId: "096", name: "Brunei", officialName: "Brunei Darussalam", capital: "Bandar Seri Begawan", continent: "Asia", areaKm2: 5765, aliases: ["brunei", "brunei darussalam"] },
  { isoCode: "BG", numericId: "100", name: "Bulgaria", officialName: "Republic of Bulgaria", capital: "Sofia", continent: "Europe", areaKm2: 110879, aliases: ["bulgaria", "bulgarie"] },
  { isoCode: "BF", numericId: "854", name: "Burkina Faso", officialName: "Burkina Faso", capital: "Ouagadougou", continent: "Africa", areaKm2: 272967, aliases: ["burkina faso", "burkina"] },
  { isoCode: "BI", numericId: "108", name: "Burundi", officialName: "Republic of Burundi", capital: "Gitega", continent: "Africa", areaKm2: 27834, aliases: ["burundi"] },
  { isoCode: "CV", numericId: "132", name: "Cabo Verde", officialName: "Republic of Cabo Verde", capital: "Praia", continent: "Africa", areaKm2: 4033, aliases: ["cabo verde", "cape verde", "cap-vert"] },
  { isoCode: "KH", numericId: "116", name: "Cambodia", officialName: "Kingdom of Cambodia", capital: "Phnom Penh", continent: "Asia", areaKm2: 181035, aliases: ["cambodia", "cambodge", "kampuchea"] },
  { isoCode: "CM", numericId: "120", name: "Cameroon", officialName: "Republic of Cameroon", capital: "Yaoundé", continent: "Africa", areaKm2: 475442, aliases: ["cameroon", "cameroun"] },
  { isoCode: "CA", numericId: "124", name: "Canada", officialName: "Canada", capital: "Ottawa", continent: "Americas", areaKm2: 9984670, aliases: ["canada"] },
  { isoCode: "CF", numericId: "140", name: "Central African Republic", officialName: "Central African Republic", capital: "Bangui", continent: "Africa", areaKm2: 622984, aliases: ["central african republic", "centrafrique", "republique centrafricaine", "république centrafricaine", "car"] },
  { isoCode: "TD", numericId: "148", name: "Chad", officialName: "Republic of Chad", capital: "N'Djamena", continent: "Africa", areaKm2: 1284000, aliases: ["chad", "tchad"] },
  { isoCode: "CL", numericId: "152", name: "Chile", officialName: "Republic of Chile", capital: "Santiago", continent: "Americas", areaKm2: 756102, aliases: ["chile", "chili"] },
  { isoCode: "CN", numericId: "156", name: "China", officialName: "People's Republic of China", capital: "Beijing", continent: "Asia", areaKm2: 9596961, aliases: ["china", "chine", "prc", "people's republic of china", "zhongguo"] },
  { isoCode: "CO", numericId: "170", name: "Colombia", officialName: "Republic of Colombia", capital: "Bogotá", continent: "Americas", areaKm2: 1141748, aliases: ["colombia", "colombie"] },
  { isoCode: "KM", numericId: "174", name: "Comoros", officialName: "Union of the Comoros", capital: "Moroni", continent: "Africa", areaKm2: 1862, aliases: ["comoros", "comores"] },
  { isoCode: "CG", numericId: "178", name: "Republic of the Congo", officialName: "Republic of the Congo", capital: "Brazzaville", continent: "Africa", areaKm2: 342000, aliases: ["republic of the congo", "congo", "congo-brazzaville", "congo brazzaville"] },
  { isoCode: "CD", numericId: "180", name: "DR Congo", officialName: "Democratic Republic of the Congo", capital: "Kinshasa", continent: "Africa", areaKm2: 2344858, aliases: ["dr congo", "drc", "democratic republic of the congo", "rdc", "republique democratique du congo", "république démocratique du congo", "congo-kinshasa", "zaire", "zaïre"] },
  { isoCode: "CR", numericId: "188", name: "Costa Rica", officialName: "Republic of Costa Rica", capital: "San José", continent: "Americas", areaKm2: 51100, aliases: ["costa rica"] },
  { isoCode: "CI", numericId: "384", name: "Ivory Coast", officialName: "Republic of Côte d'Ivoire", capital: "Yamoussoukro", continent: "Africa", areaKm2: 322463, aliases: ["ivory coast", "cote d'ivoire", "côte d'ivoire", "cote divoire"] },
  { isoCode: "HR", numericId: "191", name: "Croatia", officialName: "Republic of Croatia", capital: "Zagreb", continent: "Europe", areaKm2: 56594, aliases: ["croatia", "croatie", "hrvatska"] },
  { isoCode: "CU", numericId: "192", name: "Cuba", officialName: "Republic of Cuba", capital: "Havana", continent: "Americas", areaKm2: 109884, aliases: ["cuba"] },
  { isoCode: "CY", numericId: "196", name: "Cyprus", officialName: "Republic of Cyprus", capital: "Nicosia", continent: "Asia", areaKm2: 9251, aliases: ["cyprus", "chypre", "kypros"] },
  { isoCode: "CZ", numericId: "203", name: "Czech Republic", officialName: "Czech Republic", capital: "Prague", continent: "Europe", areaKm2: 78867, aliases: ["czech republic", "czechia", "tcheque", "tchèque", "republique tcheque", "république tchèque", "cesko"] },
  { isoCode: "DK", numericId: "208", name: "Denmark", officialName: "Kingdom of Denmark", capital: "Copenhagen", continent: "Europe", areaKm2: 42933, aliases: ["denmark", "danemark", "danmark"] },
  { isoCode: "DJ", numericId: "262", name: "Djibouti", officialName: "Republic of Djibouti", capital: "Djibouti", continent: "Africa", areaKm2: 23200, aliases: ["djibouti"] },
  { isoCode: "DM", numericId: "212", name: "Dominica", officialName: "Commonwealth of Dominica", capital: "Roseau", continent: "Americas", areaKm2: 751, aliases: ["dominica", "dominique"] },
  { isoCode: "DO", numericId: "214", name: "Dominican Republic", officialName: "Dominican Republic", capital: "Santo Domingo", continent: "Americas", areaKm2: 48671, aliases: ["dominican republic", "republique dominicaine", "république dominicaine"] },
  { isoCode: "EC", numericId: "218", name: "Ecuador", officialName: "Republic of Ecuador", capital: "Quito", continent: "Americas", areaKm2: 283561, aliases: ["ecuador", "equateur", "équateur"] },
  { isoCode: "EG", numericId: "818", name: "Egypt", officialName: "Arab Republic of Egypt", capital: "Cairo", continent: "Africa", areaKm2: 1001450, aliases: ["egypt", "egypte", "égypte", "misr"] },
  { isoCode: "SV", numericId: "222", name: "El Salvador", officialName: "Republic of El Salvador", capital: "San Salvador", continent: "Americas", areaKm2: 21041, aliases: ["el salvador", "salvador"] },
  { isoCode: "GQ", numericId: "226", name: "Equatorial Guinea", officialName: "Republic of Equatorial Guinea", capital: "Malabo", continent: "Africa", areaKm2: 28051, aliases: ["equatorial guinea", "guinee equatoriale", "guinée équatoriale"] },
  { isoCode: "ER", numericId: "232", name: "Eritrea", officialName: "State of Eritrea", capital: "Asmara", continent: "Africa", areaKm2: 117600, aliases: ["eritrea", "erythree", "érythrée"] },
  { isoCode: "EE", numericId: "233", name: "Estonia", officialName: "Republic of Estonia", capital: "Tallinn", continent: "Europe", areaKm2: 45227, aliases: ["estonia", "estonie", "eesti"] },
  { isoCode: "SZ", numericId: "748", name: "Eswatini", officialName: "Kingdom of Eswatini", capital: "Mbabane", continent: "Africa", areaKm2: 17364, aliases: ["eswatini", "swaziland"] },
  { isoCode: "ET", numericId: "231", name: "Ethiopia", officialName: "Federal Democratic Republic of Ethiopia", capital: "Addis Ababa", continent: "Africa", areaKm2: 1104300, aliases: ["ethiopia", "ethiopie", "éthiopie"] },
  { isoCode: "FJ", numericId: "242", name: "Fiji", officialName: "Republic of Fiji", capital: "Suva", continent: "Oceania", areaKm2: 18272, aliases: ["fiji", "fidji"] },
  { isoCode: "FI", numericId: "246", name: "Finland", officialName: "Republic of Finland", capital: "Helsinki", continent: "Europe", areaKm2: 338424, aliases: ["finland", "finlande", "suomi"] },
  { isoCode: "FR", numericId: "250", name: "France", officialName: "French Republic", capital: "Paris", continent: "Europe", areaKm2: 643801, aliases: ["france", "republique francaise", "république française"] },
  { isoCode: "GA", numericId: "266", name: "Gabon", officialName: "Gabonese Republic", capital: "Libreville", continent: "Africa", areaKm2: 267668, aliases: ["gabon"] },
  { isoCode: "GM", numericId: "270", name: "Gambia", officialName: "Republic of The Gambia", capital: "Banjul", continent: "Africa", areaKm2: 11295, aliases: ["gambia", "gambie", "the gambia"] },
  { isoCode: "GE", numericId: "268", name: "Georgia", officialName: "Georgia", capital: "Tbilisi", continent: "Asia", areaKm2: 69700, aliases: ["georgia", "georgie", "géorgie", "sakartvelo"] },
  { isoCode: "DE", numericId: "276", name: "Germany", officialName: "Federal Republic of Germany", capital: "Berlin", continent: "Europe", areaKm2: 357114, aliases: ["germany", "allemagne", "deutschland"] },
  { isoCode: "GH", numericId: "288", name: "Ghana", officialName: "Republic of Ghana", capital: "Accra", continent: "Africa", areaKm2: 238533, aliases: ["ghana"] },
  { isoCode: "GR", numericId: "300", name: "Greece", officialName: "Hellenic Republic", capital: "Athens", continent: "Europe", areaKm2: 131957, aliases: ["greece", "grece", "grèce", "hellas", "ellada"] },
  { isoCode: "GD", numericId: "308", name: "Grenada", officialName: "Grenada", capital: "Saint George's", continent: "Americas", areaKm2: 344, aliases: ["grenada", "grenade"] },
  { isoCode: "GT", numericId: "320", name: "Guatemala", officialName: "Republic of Guatemala", capital: "Guatemala City", continent: "Americas", areaKm2: 108889, aliases: ["guatemala"] },
  { isoCode: "GN", numericId: "324", name: "Guinea", officialName: "Republic of Guinea", capital: "Conakry", continent: "Africa", areaKm2: 245857, aliases: ["guinea", "guinee", "guinée"] },
  { isoCode: "GW", numericId: "624", name: "Guinea-Bissau", officialName: "Republic of Guinea-Bissau", capital: "Bissau", continent: "Africa", areaKm2: 36125, aliases: ["guinea-bissau", "guinee-bissau", "guinée-bissau", "guinea bissau"] },
  { isoCode: "GY", numericId: "328", name: "Guyana", officialName: "Co-operative Republic of Guyana", capital: "Georgetown", continent: "Americas", areaKm2: 214969, aliases: ["guyana"] },
  { isoCode: "HT", numericId: "332", name: "Haiti", officialName: "Republic of Haiti", capital: "Port-au-Prince", continent: "Americas", areaKm2: 27750, aliases: ["haiti", "haïti"] },
  { isoCode: "HN", numericId: "340", name: "Honduras", officialName: "Republic of Honduras", capital: "Tegucigalpa", continent: "Americas", areaKm2: 112492, aliases: ["honduras"] },
  { isoCode: "HU", numericId: "348", name: "Hungary", officialName: "Hungary", capital: "Budapest", continent: "Europe", areaKm2: 93028, aliases: ["hungary", "hongrie", "magyarorszag"] },
  { isoCode: "IS", numericId: "352", name: "Iceland", officialName: "Iceland", capital: "Reykjavík", continent: "Europe", areaKm2: 103000, aliases: ["iceland", "islande", "island"] },
  { isoCode: "IN", numericId: "356", name: "India", officialName: "Republic of India", capital: "New Delhi", continent: "Asia", areaKm2: 3287263, aliases: ["india", "inde", "bharat"] },
  { isoCode: "ID", numericId: "360", name: "Indonesia", officialName: "Republic of Indonesia", capital: "Jakarta", continent: "Asia", areaKm2: 1904569, aliases: ["indonesia", "indonesie", "indonésie"] },
  { isoCode: "IR", numericId: "364", name: "Iran", officialName: "Islamic Republic of Iran", capital: "Tehran", continent: "Asia", areaKm2: 1648195, aliases: ["iran", "persia", "perse"] },
  { isoCode: "IQ", numericId: "368", name: "Iraq", officialName: "Republic of Iraq", capital: "Baghdad", continent: "Asia", areaKm2: 438317, aliases: ["iraq", "irak"] },
  { isoCode: "IE", numericId: "372", name: "Ireland", officialName: "Ireland", capital: "Dublin", continent: "Europe", areaKm2: 70273, aliases: ["ireland", "irlande", "eire"] },
  { isoCode: "IL", numericId: "376", name: "Israel", officialName: "State of Israel", capital: "Jerusalem", continent: "Asia", areaKm2: 20770, aliases: ["israel", "israël"] },
  { isoCode: "IT", numericId: "380", name: "Italy", officialName: "Italian Republic", capital: "Rome", continent: "Europe", areaKm2: 301340, aliases: ["italy", "italie", "italia"] },
  { isoCode: "JM", numericId: "388", name: "Jamaica", officialName: "Jamaica", capital: "Kingston", continent: "Americas", areaKm2: 10991, aliases: ["jamaica", "jamaique", "jamaïque"] },
  { isoCode: "JP", numericId: "392", name: "Japan", officialName: "Japan", capital: "Tokyo", continent: "Asia", areaKm2: 377975, aliases: ["japan", "japon", "nihon", "nippon"] },
  { isoCode: "JO", numericId: "400", name: "Jordan", officialName: "Hashemite Kingdom of Jordan", capital: "Amman", continent: "Asia", areaKm2: 89342, aliases: ["jordan", "jordanie"] },
  { isoCode: "KZ", numericId: "398", name: "Kazakhstan", officialName: "Republic of Kazakhstan", capital: "Astana", continent: "Asia", areaKm2: 2724900, aliases: ["kazakhstan"] },
  { isoCode: "KE", numericId: "404", name: "Kenya", officialName: "Republic of Kenya", capital: "Nairobi", continent: "Africa", areaKm2: 580367, aliases: ["kenya"] },
  { isoCode: "KI", numericId: "296", name: "Kiribati", officialName: "Republic of Kiribati", capital: "Tarawa", continent: "Oceania", areaKm2: 811, aliases: ["kiribati"] },
  { isoCode: "KP", numericId: "408", name: "North Korea", officialName: "Democratic People's Republic of Korea", capital: "Pyongyang", continent: "Asia", areaKm2: 120538, aliases: ["north korea", "coree du nord", "corée du nord", "dprk", "democratic people's republic of korea"] },
  { isoCode: "KR", numericId: "410", name: "South Korea", officialName: "Republic of Korea", capital: "Seoul", continent: "Asia", areaKm2: 100210, aliases: ["south korea", "coree du sud", "corée du sud", "republic of korea", "rok"] },
  { isoCode: "KW", numericId: "414", name: "Kuwait", officialName: "State of Kuwait", capital: "Kuwait City", continent: "Asia", areaKm2: 17818, aliases: ["kuwait", "koweit", "koweït"] },
  { isoCode: "KG", numericId: "417", name: "Kyrgyzstan", officialName: "Kyrgyz Republic", capital: "Bishkek", continent: "Asia", areaKm2: 199951, aliases: ["kyrgyzstan", "kirghizistan", "kirghizstan"] },
  { isoCode: "LA", numericId: "418", name: "Laos", officialName: "Lao People's Democratic Republic", capital: "Vientiane", continent: "Asia", areaKm2: 236800, aliases: ["laos"] },
  { isoCode: "LV", numericId: "428", name: "Latvia", officialName: "Republic of Latvia", capital: "Riga", continent: "Europe", areaKm2: 64589, aliases: ["latvia", "lettonie", "latvija"] },
  { isoCode: "LB", numericId: "422", name: "Lebanon", officialName: "Lebanese Republic", capital: "Beirut", continent: "Asia", areaKm2: 10452, aliases: ["lebanon", "liban"] },
  { isoCode: "LS", numericId: "426", name: "Lesotho", officialName: "Kingdom of Lesotho", capital: "Maseru", continent: "Africa", areaKm2: 30355, aliases: ["lesotho"] },
  { isoCode: "LR", numericId: "430", name: "Liberia", officialName: "Republic of Liberia", capital: "Monrovia", continent: "Africa", areaKm2: 111369, aliases: ["liberia"] },
  { isoCode: "LY", numericId: "434", name: "Libya", officialName: "State of Libya", capital: "Tripoli", continent: "Africa", areaKm2: 1759540, aliases: ["libya", "libye"] },
  { isoCode: "LI", numericId: "438", name: "Liechtenstein", officialName: "Principality of Liechtenstein", capital: "Vaduz", continent: "Europe", areaKm2: 160, aliases: ["liechtenstein"] },
  { isoCode: "LT", numericId: "440", name: "Lithuania", officialName: "Republic of Lithuania", capital: "Vilnius", continent: "Europe", areaKm2: 65300, aliases: ["lithuania", "lituanie", "lietuva"] },
  { isoCode: "LU", numericId: "442", name: "Luxembourg", officialName: "Grand Duchy of Luxembourg", capital: "Luxembourg", continent: "Europe", areaKm2: 2586, aliases: ["luxembourg"] },
  { isoCode: "MG", numericId: "450", name: "Madagascar", officialName: "Republic of Madagascar", capital: "Antananarivo", continent: "Africa", areaKm2: 587041, aliases: ["madagascar"] },
  { isoCode: "MW", numericId: "454", name: "Malawi", officialName: "Republic of Malawi", capital: "Lilongwe", continent: "Africa", areaKm2: 118484, aliases: ["malawi"] },
  { isoCode: "MY", numericId: "458", name: "Malaysia", officialName: "Malaysia", capital: "Kuala Lumpur", continent: "Asia", areaKm2: 330803, aliases: ["malaysia", "malaisie"] },
  { isoCode: "MV", numericId: "462", name: "Maldives", officialName: "Republic of Maldives", capital: "Malé", continent: "Asia", areaKm2: 298, aliases: ["maldives"] },
  { isoCode: "ML", numericId: "466", name: "Mali", officialName: "Republic of Mali", capital: "Bamako", continent: "Africa", areaKm2: 1240192, aliases: ["mali"] },
  { isoCode: "MT", numericId: "470", name: "Malta", officialName: "Republic of Malta", capital: "Valletta", continent: "Europe", areaKm2: 316, aliases: ["malta", "malte"] },
  { isoCode: "MH", numericId: "584", name: "Marshall Islands", officialName: "Republic of the Marshall Islands", capital: "Majuro", continent: "Oceania", areaKm2: 181, aliases: ["marshall islands", "iles marshall", "îles marshall"] },
  { isoCode: "MR", numericId: "478", name: "Mauritania", officialName: "Islamic Republic of Mauritania", capital: "Nouakchott", continent: "Africa", areaKm2: 1030700, aliases: ["mauritania", "mauritanie"] },
  { isoCode: "MU", numericId: "480", name: "Mauritius", officialName: "Republic of Mauritius", capital: "Port Louis", continent: "Africa", areaKm2: 2040, aliases: ["mauritius", "maurice", "ile maurice"] },
  { isoCode: "MX", numericId: "484", name: "Mexico", officialName: "United Mexican States", capital: "Mexico City", continent: "Americas", areaKm2: 1964375, aliases: ["mexico", "mexique", "mexico city"] },
  { isoCode: "FM", numericId: "583", name: "Micronesia", officialName: "Federated States of Micronesia", capital: "Palikir", continent: "Oceania", areaKm2: 702, aliases: ["micronesia", "micronesie", "micronésie"] },
  { isoCode: "MD", numericId: "498", name: "Moldova", officialName: "Republic of Moldova", capital: "Chișinău", continent: "Europe", areaKm2: 33846, aliases: ["moldova", "moldavie"] },
  { isoCode: "MC", numericId: "492", name: "Monaco", officialName: "Principality of Monaco", capital: "Monaco", continent: "Europe", areaKm2: 2, aliases: ["monaco"] },
  { isoCode: "MN", numericId: "496", name: "Mongolia", officialName: "Mongolia", capital: "Ulaanbaatar", continent: "Asia", areaKm2: 1564110, aliases: ["mongolia", "mongolie"] },
  { isoCode: "ME", numericId: "499", name: "Montenegro", officialName: "Montenegro", capital: "Podgorica", continent: "Europe", areaKm2: 13812, aliases: ["montenegro", "monténégro", "crna gora"] },
  { isoCode: "MA", numericId: "504", name: "Morocco", officialName: "Kingdom of Morocco", capital: "Rabat", continent: "Africa", areaKm2: 446550, aliases: ["morocco", "maroc", "al-maghrib"] },
  { isoCode: "MZ", numericId: "508", name: "Mozambique", officialName: "Republic of Mozambique", capital: "Maputo", continent: "Africa", areaKm2: 801590, aliases: ["mozambique"] },
  { isoCode: "MM", numericId: "104", name: "Myanmar", officialName: "Republic of the Union of Myanmar", capital: "Naypyidaw", continent: "Asia", areaKm2: 676578, aliases: ["myanmar", "burma", "birmanie"] },
  { isoCode: "NA", numericId: "516", name: "Namibia", officialName: "Republic of Namibia", capital: "Windhoek", continent: "Africa", areaKm2: 825615, aliases: ["namibia", "namibie"] },
  { isoCode: "NR", numericId: "520", name: "Nauru", officialName: "Republic of Nauru", capital: "Yaren", continent: "Oceania", areaKm2: 21, aliases: ["nauru"] },
  { isoCode: "NP", numericId: "524", name: "Nepal", officialName: "Federal Democratic Republic of Nepal", capital: "Kathmandu", continent: "Asia", areaKm2: 147181, aliases: ["nepal", "népal"] },
  { isoCode: "NL", numericId: "528", name: "Netherlands", officialName: "Kingdom of the Netherlands", capital: "Amsterdam", continent: "Europe", areaKm2: 41850, aliases: ["netherlands", "pays-bas", "pays bas", "nederland", "holland", "hollande"] },
  { isoCode: "NZ", numericId: "554", name: "New Zealand", officialName: "New Zealand", capital: "Wellington", continent: "Oceania", areaKm2: 268021, aliases: ["new zealand", "nouvelle-zelande", "nouvelle-zélande", "aotearoa"] },
  { isoCode: "NI", numericId: "558", name: "Nicaragua", officialName: "Republic of Nicaragua", capital: "Managua", continent: "Americas", areaKm2: 130373, aliases: ["nicaragua"] },
  { isoCode: "NE", numericId: "562", name: "Niger", officialName: "Republic of the Niger", capital: "Niamey", continent: "Africa", areaKm2: 1267000, aliases: ["niger"] },
  { isoCode: "NG", numericId: "566", name: "Nigeria", officialName: "Federal Republic of Nigeria", capital: "Abuja", continent: "Africa", areaKm2: 923768, aliases: ["nigeria"] },
  { isoCode: "MK", numericId: "807", name: "North Macedonia", officialName: "Republic of North Macedonia", capital: "Skopje", continent: "Europe", areaKm2: 25713, aliases: ["north macedonia", "macedoine du nord", "macédoine du nord", "macedonia", "macedoine", "macédoine"] },
  { isoCode: "NO", numericId: "578", name: "Norway", officialName: "Kingdom of Norway", capital: "Oslo", continent: "Europe", areaKm2: 323802, aliases: ["norway", "norvege", "norvège", "norge"] },
  { isoCode: "OM", numericId: "512", name: "Oman", officialName: "Sultanate of Oman", capital: "Muscat", continent: "Asia", areaKm2: 309500, aliases: ["oman"] },
  { isoCode: "PK", numericId: "586", name: "Pakistan", officialName: "Islamic Republic of Pakistan", capital: "Islamabad", continent: "Asia", areaKm2: 881913, aliases: ["pakistan"] },
  { isoCode: "PW", numericId: "585", name: "Palau", officialName: "Republic of Palau", capital: "Ngerulmud", continent: "Oceania", areaKm2: 459, aliases: ["palau", "palaos"] },
  { isoCode: "PA", numericId: "591", name: "Panama", officialName: "Republic of Panama", capital: "Panama City", continent: "Americas", areaKm2: 75417, aliases: ["panama"] },
  { isoCode: "PG", numericId: "598", name: "Papua New Guinea", officialName: "Independent State of Papua New Guinea", capital: "Port Moresby", continent: "Oceania", areaKm2: 462840, aliases: ["papua new guinea", "papouasie nouvelle guinee", "papouasie-nouvelle-guinée", "png"] },
  { isoCode: "PY", numericId: "600", name: "Paraguay", officialName: "Republic of Paraguay", capital: "Asunción", continent: "Americas", areaKm2: 406752, aliases: ["paraguay"] },
  { isoCode: "PE", numericId: "604", name: "Peru", officialName: "Republic of Peru", capital: "Lima", continent: "Americas", areaKm2: 1285216, aliases: ["peru", "perou", "pérou"] },
  { isoCode: "PH", numericId: "608", name: "Philippines", officialName: "Republic of the Philippines", capital: "Manila", continent: "Asia", areaKm2: 300000, aliases: ["philippines", "filipinas", "pilipinas"] },
  { isoCode: "PL", numericId: "616", name: "Poland", officialName: "Republic of Poland", capital: "Warsaw", continent: "Europe", areaKm2: 312696, aliases: ["poland", "pologne", "polska"] },
  { isoCode: "PT", numericId: "620", name: "Portugal", officialName: "Portuguese Republic", capital: "Lisbon", continent: "Europe", areaKm2: 92212, aliases: ["portugal"] },
  { isoCode: "QA", numericId: "634", name: "Qatar", officialName: "State of Qatar", capital: "Doha", continent: "Asia", areaKm2: 11586, aliases: ["qatar"] },
  { isoCode: "RO", numericId: "642", name: "Romania", officialName: "Romania", capital: "Bucharest", continent: "Europe", areaKm2: 238397, aliases: ["romania", "roumanie", "romania"] },
  { isoCode: "RU", numericId: "643", name: "Russia", officialName: "Russian Federation", capital: "Moscow", continent: "Europe", areaKm2: 17098246, aliases: ["russia", "russie", "rossiya", "russian federation"] },
  { isoCode: "RW", numericId: "646", name: "Rwanda", officialName: "Republic of Rwanda", capital: "Kigali", continent: "Africa", areaKm2: 26338, aliases: ["rwanda"] },
  { isoCode: "KN", numericId: "659", name: "Saint Kitts and Nevis", officialName: "Federation of Saint Christopher and Nevis", capital: "Basseterre", continent: "Americas", areaKm2: 261, aliases: ["saint kitts and nevis", "saint-kitts-et-nevis", "st kitts and nevis"] },
  { isoCode: "LC", numericId: "662", name: "Saint Lucia", officialName: "Saint Lucia", capital: "Castries", continent: "Americas", areaKm2: 617, aliases: ["saint lucia", "sainte lucie", "sainte-lucie"] },
  { isoCode: "VC", numericId: "670", name: "Saint Vincent and the Grenadines", officialName: "Saint Vincent and the Grenadines", capital: "Kingstown", continent: "Americas", areaKm2: 389, aliases: ["saint vincent and the grenadines", "saint vincent", "saint-vincent-et-les-grenadines"] },
  { isoCode: "WS", numericId: "882", name: "Samoa", officialName: "Independent State of Samoa", capital: "Apia", continent: "Oceania", areaKm2: 2842, aliases: ["samoa"] },
  { isoCode: "SM", numericId: "674", name: "San Marino", officialName: "Republic of San Marino", capital: "San Marino", continent: "Europe", areaKm2: 61, aliases: ["san marino", "saint-marin", "saint marin"] },
  { isoCode: "ST", numericId: "678", name: "São Tomé and Príncipe", officialName: "Democratic Republic of São Tomé and Príncipe", capital: "São Tomé", continent: "Africa", areaKm2: 964, aliases: ["sao tome and principe", "sao tome", "são tomé et principe", "sao tome et principe"] },
  { isoCode: "SA", numericId: "682", name: "Saudi Arabia", officialName: "Kingdom of Saudi Arabia", capital: "Riyadh", continent: "Asia", areaKm2: 2149690, aliases: ["saudi arabia", "arabie saoudite", "ksa"] },
  { isoCode: "SN", numericId: "686", name: "Senegal", officialName: "Republic of Senegal", capital: "Dakar", continent: "Africa", areaKm2: 196722, aliases: ["senegal", "sénégal"] },
  { isoCode: "RS", numericId: "688", name: "Serbia", officialName: "Republic of Serbia", capital: "Belgrade", continent: "Europe", areaKm2: 88361, aliases: ["serbia", "serbie", "srbija"] },
  // Note: Kosovo has no ISO-3166 numeric code. The world-atlas topojson tags it as "-99"
  // (Natural Earth sentinel for disputed/unassigned). Keeping that here so the map paints it.
  { isoCode: "XK", numericId: "-99", name: "Kosovo", officialName: "Republic of Kosovo", capital: "Pristina", continent: "Europe", areaKm2: 10887, aliases: ["kosovo", "kosova", "republic of kosovo"] },
  { isoCode: "SC", numericId: "690", name: "Seychelles", officialName: "Republic of Seychelles", capital: "Victoria", continent: "Africa", areaKm2: 459, aliases: ["seychelles"] },
  { isoCode: "SL", numericId: "694", name: "Sierra Leone", officialName: "Republic of Sierra Leone", capital: "Freetown", continent: "Africa", areaKm2: 71740, aliases: ["sierra leone"] },
  { isoCode: "SG", numericId: "702", name: "Singapore", officialName: "Republic of Singapore", capital: "Singapore", continent: "Asia", areaKm2: 728, aliases: ["singapore", "singapour"] },
  { isoCode: "SK", numericId: "703", name: "Slovakia", officialName: "Slovak Republic", capital: "Bratislava", continent: "Europe", areaKm2: 49035, aliases: ["slovakia", "slovaquie", "slovensko"] },
  { isoCode: "SI", numericId: "705", name: "Slovenia", officialName: "Republic of Slovenia", capital: "Ljubljana", continent: "Europe", areaKm2: 20273, aliases: ["slovenia", "slovenie", "slovénie", "slovenija"] },
  { isoCode: "SB", numericId: "090", name: "Solomon Islands", officialName: "Solomon Islands", capital: "Honiara", continent: "Oceania", areaKm2: 28896, aliases: ["solomon islands", "iles salomon", "îles salomon"] },
  { isoCode: "SO", numericId: "706", name: "Somalia", officialName: "Federal Republic of Somalia", capital: "Mogadishu", continent: "Africa", areaKm2: 637657, aliases: ["somalia", "somalie"] },
  { isoCode: "ZA", numericId: "710", name: "South Africa", officialName: "Republic of South Africa", capital: "Pretoria", continent: "Africa", areaKm2: 1221037, aliases: ["south africa", "afrique du sud", "rsa"] },
  { isoCode: "SS", numericId: "728", name: "South Sudan", officialName: "Republic of South Sudan", capital: "Juba", continent: "Africa", areaKm2: 644329, aliases: ["south sudan", "soudan du sud"] },
  { isoCode: "ES", numericId: "724", name: "Spain", officialName: "Kingdom of Spain", capital: "Madrid", continent: "Europe", areaKm2: 505992, aliases: ["spain", "espagne", "espana", "españa"] },
  { isoCode: "LK", numericId: "144", name: "Sri Lanka", officialName: "Democratic Socialist Republic of Sri Lanka", capital: "Sri Jayawardenepura Kotte", continent: "Asia", areaKm2: 65610, aliases: ["sri lanka", "ceylon", "ceylan"] },
  { isoCode: "SD", numericId: "729", name: "Sudan", officialName: "Republic of the Sudan", capital: "Khartoum", continent: "Africa", areaKm2: 1861484, aliases: ["sudan", "soudan"] },
  { isoCode: "SR", numericId: "740", name: "Suriname", officialName: "Republic of Suriname", capital: "Paramaribo", continent: "Americas", areaKm2: 163820, aliases: ["suriname", "surinam"] },
  { isoCode: "SE", numericId: "752", name: "Sweden", officialName: "Kingdom of Sweden", capital: "Stockholm", continent: "Europe", areaKm2: 450295, aliases: ["sweden", "suede", "suède", "sverige"] },
  { isoCode: "CH", numericId: "756", name: "Switzerland", officialName: "Swiss Confederation", capital: "Bern", continent: "Europe", areaKm2: 41285, aliases: ["switzerland", "suisse", "schweiz", "svizzera", "helvetia"] },
  { isoCode: "SY", numericId: "760", name: "Syria", officialName: "Syrian Arab Republic", capital: "Damascus", continent: "Asia", areaKm2: 185180, aliases: ["syria", "syrie"] },
  { isoCode: "TW", numericId: "158", name: "Taiwan", officialName: "Republic of China", capital: "Taipei", continent: "Asia", areaKm2: 36197, aliases: ["taiwan", "taïwan", "republic of china", "roc", "formosa", "formose", "chinese taipei"] },
  { isoCode: "TJ", numericId: "762", name: "Tajikistan", officialName: "Republic of Tajikistan", capital: "Dushanbe", continent: "Asia", areaKm2: 143100, aliases: ["tajikistan", "tadjikistan"] },
  { isoCode: "TZ", numericId: "834", name: "Tanzania", officialName: "United Republic of Tanzania", capital: "Dodoma", continent: "Africa", areaKm2: 945087, aliases: ["tanzania", "tanzanie"] },
  { isoCode: "TH", numericId: "764", name: "Thailand", officialName: "Kingdom of Thailand", capital: "Bangkok", continent: "Asia", areaKm2: 513120, aliases: ["thailand", "thailande", "thaïlande", "siam"] },
  { isoCode: "TL", numericId: "626", name: "Timor-Leste", officialName: "Democratic Republic of Timor-Leste", capital: "Dili", continent: "Asia", areaKm2: 14874, aliases: ["timor-leste", "timor leste", "east timor", "timor oriental"] },
  { isoCode: "TG", numericId: "768", name: "Togo", officialName: "Togolese Republic", capital: "Lomé", continent: "Africa", areaKm2: 56785, aliases: ["togo"] },
  { isoCode: "TO", numericId: "776", name: "Tonga", officialName: "Kingdom of Tonga", capital: "Nuku'alofa", continent: "Oceania", areaKm2: 747, aliases: ["tonga"] },
  { isoCode: "TT", numericId: "780", name: "Trinidad and Tobago", officialName: "Republic of Trinidad and Tobago", capital: "Port of Spain", continent: "Americas", areaKm2: 5130, aliases: ["trinidad and tobago", "trinite et tobago", "trinité et tobago"] },
  { isoCode: "TN", numericId: "788", name: "Tunisia", officialName: "Republic of Tunisia", capital: "Tunis", continent: "Africa", areaKm2: 163610, aliases: ["tunisia", "tunisie"] },
  { isoCode: "TR", numericId: "792", name: "Turkey", officialName: "Republic of Türkiye", capital: "Ankara", continent: "Asia", areaKm2: 783562, aliases: ["turkey", "turquie", "turkiye", "türkiye"] },
  { isoCode: "TM", numericId: "795", name: "Turkmenistan", officialName: "Turkmenistan", capital: "Ashgabat", continent: "Asia", areaKm2: 488100, aliases: ["turkmenistan", "turkmenistan"] },
  { isoCode: "TV", numericId: "798", name: "Tuvalu", officialName: "Tuvalu", capital: "Funafuti", continent: "Oceania", areaKm2: 26, aliases: ["tuvalu"] },
  { isoCode: "UG", numericId: "800", name: "Uganda", officialName: "Republic of Uganda", capital: "Kampala", continent: "Africa", areaKm2: 241038, aliases: ["uganda", "ouganda"] },
  { isoCode: "UA", numericId: "804", name: "Ukraine", officialName: "Ukraine", capital: "Kyiv", continent: "Europe", areaKm2: 603500, aliases: ["ukraine"] },
  { isoCode: "AE", numericId: "784", name: "United Arab Emirates", officialName: "United Arab Emirates", capital: "Abu Dhabi", continent: "Asia", areaKm2: 83600, aliases: ["united arab emirates", "uae", "emirats arabes unis", "émirats arabes unis", "emirates"] },
  { isoCode: "GB", numericId: "826", name: "United Kingdom", officialName: "United Kingdom of Great Britain and Northern Ireland", capital: "London", continent: "Europe", areaKm2: 243610, aliases: ["united kingdom", "uk", "great britain", "britain", "royaume-uni", "royaume uni", "grande bretagne"] },
  { isoCode: "US", numericId: "840", name: "United States", officialName: "United States of America", capital: "Washington, D.C.", continent: "Americas", areaKm2: 9833517, aliases: ["united states", "united states of america", "usa", "us", "america", "etats-unis", "états-unis", "etats unis"] },
  { isoCode: "UY", numericId: "858", name: "Uruguay", officialName: "Oriental Republic of Uruguay", capital: "Montevideo", continent: "Americas", areaKm2: 181034, aliases: ["uruguay"] },
  { isoCode: "UZ", numericId: "860", name: "Uzbekistan", officialName: "Republic of Uzbekistan", capital: "Tashkent", continent: "Asia", areaKm2: 447400, aliases: ["uzbekistan", "ouzbekistan", "ouzbékistan"] },
  { isoCode: "VU", numericId: "548", name: "Vanuatu", officialName: "Republic of Vanuatu", capital: "Port Vila", continent: "Oceania", areaKm2: 12189, aliases: ["vanuatu"] },
  // Note: Vatican City (0.49 km²) is too small to render in the 110m world topojson —
  // it remains matchable as a guess but won't appear colored on the map.
  { isoCode: "VA", numericId: "336", name: "Vatican City", officialName: "Holy See", capital: "Vatican City", continent: "Europe", areaKm2: 0.49, aliases: ["vatican", "vatican city", "holy see", "saint-siege", "saint siege", "saint-siège", "cite du vatican", "cité du vatican"] },
  { isoCode: "VE", numericId: "862", name: "Venezuela", officialName: "Bolivarian Republic of Venezuela", capital: "Caracas", continent: "Americas", areaKm2: 916445, aliases: ["venezuela"] },
  { isoCode: "VN", numericId: "704", name: "Vietnam", officialName: "Socialist Republic of Vietnam", capital: "Hanoi", continent: "Asia", areaKm2: 331212, aliases: ["vietnam", "viet nam"] },
  { isoCode: "YE", numericId: "887", name: "Yemen", officialName: "Republic of Yemen", capital: "Sana'a", continent: "Asia", areaKm2: 527968, aliases: ["yemen", "yémen"] },
  { isoCode: "ZM", numericId: "894", name: "Zambia", officialName: "Republic of Zambia", capital: "Lusaka", continent: "Africa", areaKm2: 752618, aliases: ["zambia", "zambie"] },
  { isoCode: "ZW", numericId: "716", name: "Zimbabwe", officialName: "Republic of Zimbabwe", capital: "Harare", continent: "Africa", areaKm2: 390757, aliases: ["zimbabwe"] }
];

export const TOTAL_WORLD_AREA_KM2 = COUNTRIES.reduce((s, c) => s + c.areaKm2, 0);

export const ISO_BY_NUMERIC: Record<string, string> = COUNTRIES.reduce((acc, c) => {
  acc[c.numericId] = c.isoCode;
  return acc;
}, {} as Record<string, string>);

export const BY_ISO: Record<string, Country> = COUNTRIES.reduce((acc, c) => {
  acc[c.isoCode] = c;
  return acc;
}, {} as Record<string, Country>);
